title: Deepak Gopinath
logo: /assets/img/headshot.jpg
description:
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
gems:
  - jekyll-sitemap
plugins:
  - jekyll-sitemap
whitelist:
  - jekyll-sitemap
